# Generated by Django 3.0.5 on 2020-09-20 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20200917_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='content_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reviews',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
