# Generated by Django 3.0.5 on 2020-09-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20200920_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='readability_rating',
            field=models.IntegerField(default=1),
        ),
    ]
