# Generated by Django 3.0.5 on 2020-09-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_reviews_readability_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='comprehensibility_rating',
            field=models.IntegerField(default=1),
        ),
    ]
