# Generated by Django 3.0.5 on 2020-09-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_reviews_comprehensibility_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='image',
            field=models.ImageField(null=True, upload_to='reviews/'),
        ),
    ]
