# Generated by Django 3.0.5 on 2020-09-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20200922_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='image',
            field=models.ImageField(default='bookcover5.jpg', upload_to='static/'),
        ),
    ]
