# Generated by Django 3.0.5 on 2020-09-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20200923_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='comprehensibility_rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='image',
            field=models.ImageField(default='bookcover5.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='readability_rating',
            field=models.IntegerField(default=4),
        ),
    ]
