# Generated by Django 3.0.5 on 2020-09-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20200923_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='image',
            field=models.ImageField(default='bookcover1s.jpg', upload_to=''),
        ),
    ]
